config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :posts
    resources :colors
  end

  get 'about', to: 'pages#about'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'



  resources :users
  resource :profile, only: %i[show edit update]

  resources :color_palettes do
    post 'analyze', on: :collection
  end

  resources :posts, shallow: true do
    resources :categories
  end

  resources :posts do
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

  resources :posts do   
    resources :comments, only: [:create, :destroy]  
  end

  resources :color_palettes do
    delete :delete, on: :member
  end

  resources :posts do
    collection do
      get :search, to: 'posts#search'
    end
  end

  get 'bookmarked_posts', to: 'posts#bookmarked'

  resources :users do
    resources :posts
  end

  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  enum role: { general: 0, admin: 1 }

  has_many :color_palettes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :bookmarks
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  has_many :comments

  validates :name, presence: true, length: { maximum: 255 }
  validates :password, length: { minimum: 3 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true


  def bookmark(post)
    bookmarked_posts << post
  end

  def unbookmark(post)
    bookmarked_posts.destroy(post)
  end

  def bookmark?(post)
    bookmarked_posts.include?(post)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc)
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: User.model_name.human)
      render 'edit'
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_admin, only: %i[index]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find(params[:id])
    @color_palettes = @user.color_palettes.includes(:colors)
    @posts = @user.posts
    @bookmarked_posts = current_user.bookmarked_posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_url(@user), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :name)
  end

  def require_admin
    unless current_user.admin?
      flash[:alert] = 'You must be an admin to access this page.'
      redirect_to root_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="wrapper">
      <h3 class="form-signin-heading">Sign up to ColorTips!</h3>
      <hr class="colorgraph"><br>
      <div class="form-group">
        <%= form.text_field :name, class: 'form-control', placeholder: "Name"  %>
      </div>

      <div class="form-group">
        <%= form.text_field :email, class: 'form-control', placeholder: "Email"  %>
      </div>

      <div class="form-group">
        <%= form.password_field :password, class: 'form-control', placeholder: "Password"  %>
      </div>
      
      <div class="form-group">
        <%= form.password_field :password_confirmation,class: 'form-control', placeholder: "Password Confirmation" %>
      </div>

      <button class="btn btn-lg btn-primary btn-block"  name="Submit" type="Submit">Crate User</button>  

      <div class='text-center'>
        <%= link_to 'login page', login_path %>
      </div>
  </div>        
</div>  
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="new-user-container">
  <%= render 'form', user: @user %>
</div>  

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5">
  <div class="card">
      <div class="card-body d-flex flex-column align-items-center">
          <%= image_tag current_user.avatar.url, class: 'rounded-circle', size: '120x120' %>
          <h1 class="my-3"><strong><%= @user.name %></strong></h1>
          <p class="mb-3"><%= "@" + @user.name %></p>
          <p class="mb-3"><strong>Address:</strong> <%= @user.email %></p>
          <div class="edit-link mt-auto">
              <%= link_to t('defaults.edit'), edit_profile_path, class: "btn btn-primary" %>
          </div>
      </div>
  </div>
</div>  


<div class="container mt-5">
  <div class="card mx-auto" style="width: 100%; max-width: 1500px;">
    <div class="card-header bg-light">Your ColorPalettes</div>
    <div class="card-body">
      <div class="row justify-content-start">
        <% @color_palettes.each do |color_palette| %>
          <div class="col-auto mb-3">
            <div class="" style="width: 5rem;">
              <div class="card-body">
                <h3 style="font-size: 10px;"><%= color_palette.color_palette_title %></h3>
                <div class="color_palette">
                  <% color_palette.colors.each do |color| %>
                    <div class="color-row custom-width" style="height: 15px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                  <% end %>
                </div>
                <% if current_user == color_palette.user %>
                  <%= link_to delete_color_palette_path(color_palette), method: :delete, class: 'delete-color-palette', data: { confirm: 'Are you sure you want to delete this color palette?' } do %>
                    <i class="fa-solid fa-trash-can"></i>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>  


<div class="container mt-5">
  <div class="card mx-auto" style="width: 100%; max-width: 1500px;">
    <div class="card-header bg-light">Your Posts</div>
      <div class="card-body">
        <div class="container-userpage">
          <% @posts.each do |post| %>
            <div class="row1">
              <div class="col-sm-2">
                  <div class="row"> 
                      <div class="color-palette">
                          <% post.color_palette.colors.each do |color| %>
                              <div class="color-row" style="width: 28px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                          <% end %>
                      </div>
                  </div>
                  <div class="row">      
                      <div class="image-container">
                        <%= link_to post_path(post), class: 'btn', remote: true, data: { toggle: 'modal', target: '#postModal' } do %>
                            <% if post.images.any? %>
                              <%= image_tag post.images.first.to_s, class: "postimage" %>
                            <% end %>
                        <% end %>  
                      </div>
                  </div>    
              </div>  
            </div>        
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>        
<div class="container mt-5">
  <div class="card mx-auto" style="width: 100%; max-width: 1500px;">
    <div class="card-header bg-light">Bookmarks</div>
      <div class="card-body">
        <div class="container-userpage">
          <% @bookmarked_posts.each do |post| %>
            <div class="row1">
              <div class="col-sm-2">
                  <div class="row"> 
                      <div class="color-palette">
                          <% post.color_palette.colors.each do |color| %>
                              <div class="color-row" style="width: 28px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                          <% end %>
                      </div>
                  </div>
                  <div class="row">      
                      <div class="image-container">
                        <%= link_to post_path(post), class: 'btn', remote: true, data: { toggle: 'modal', target: '#postModal' } do %>
                            <% if post.images.any? %>
                              <%= image_tag post.images.first.to_s, class: "postimage" %>
                            <% end %>
                        <% end %>  
                      </div>
                  </div>    
              </div>  
            </div>        
          <% end %>
        </div>
      </div>
    </div>
  </div>  
</div>        

<script>

  window.onload = function() {
    $(document).on('click', '.delete-color-palette', function(e) {
      e.preventDefault();
      if (confirm('Are you sure you want to delete this color palette?')) {
        var color_palette_id = $(this).data('color-palette-id');
        $.ajax({
          type: 'DELETE',
          url: '/color_palettes/' + color_palette_id,
          success: function() {
            // 削除されたカラーパレットを画面から削除する
            $(e.target).closest('.col-md-2').remove();
          },
          error: function() {
            alert('Failed to delete color palette');
          }
        });
      }
    });
  }  

</script>