config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :posts
    resources :colors
  end

  get 'about', to: 'pages#about'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'



  resources :users
  resource :profile, only: %i[show edit update]

  resources :color_palettes do
    post 'analyze', on: :collection
  end

  resources :posts, shallow: true do
    resources :categories
  end

  resources :posts do
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

  resources :posts do   
    resources :comments, only: [:create, :destroy]  
  end

  resources :color_palettes do
    delete :delete, on: :member
  end

  resources :posts do
    collection do
      get :search, to: 'posts#search'
    end
  end

  get 'bookmarked_posts', to: 'posts#bookmarked'

  resources :users do
    resources :posts
  end

  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  authenticates_with_sorcery!

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, foreign_key: :category_id, dependent: :destroy
  has_many :posts, through: :post_categories, dependent: :destroy

  validates :category_name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :color_palette_colors, dependent: :destroy
  has_many :color_palettes, through: :color_palette_colors, dependent: :destroy
end

app/models/color_palette.rb
class ColorPalette < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :color_palette_colors, dependent: :destroy
  has_many :colors, through: :color_palette_colors, dependent: :destroy
  validates :color_palette_title, presence: true
end

app/models/color_palette_color.rb
class ColorPaletteColor < ApplicationRecord
  belongs_to :color_palette
  belongs_to :color
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploaders :images, ImageUploader
  belongs_to :user
  belongs_to :color_palette
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :bookmarks, source: :user
  has_many :comments, dependent: :destroy
  validates :color_palette_id, presence: { message: 'カラーパレットを選択してください' }
  validates :images, presence: { message: '画像を選択してください' }

  attr_accessor :category_names

  def save_category(sent_categories)
    categories.clear # 一旦現在のカテゴリを全て削除する
    sent_categories.each do |category_name|
      category = Category.find_or_create_by(category_name: category_name)
      categories << category unless categories.include?(category)
    end
  end

  def selected_colors
    self.color_palette.color_palette_colors.sample(2).map(&:color)
  end

  
  def recommended_posts
    Post.joins(color_palette: :color_palette_colors)
        .where(color_palette_colors: { color_id: self.selected_colors.map(&:id) })
        .where.not(id: self.id)
        .distinct
  end
  
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category

  validates :post_id, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  mount_uploader :avatar, AvatarUploader

  enum role: { general: 0, admin: 1 }

  has_many :color_palettes, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :bookmarks
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  has_many :comments

  validates :name, presence: true, length: { maximum: 255 }
  validates :password, length: { minimum: 3 }, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true


  def bookmark(post)
    bookmarked_posts << post
  end

  def unbookmark(post)
    bookmarked_posts.destroy(post)
  end

  def bookmark?(post)
    bookmarked_posts.include?(post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_login, except: [:about]

  def about; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: %i[index show]

  def index
    @posts = Post.all.includes(:user).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html { render 'posts/_show' }
      format.js 
    end
  end
  

  def new
    @post = Post.new(user_id: current_user.id)
    @color_palettes = current_user.color_palettes
  end

  def create
    @post = current_user.posts.build(post_params)
    category_list = params[:post][:category_name].split(',')
    if @post.save
      @post.save_category(category_list)
      redirect_to root_path(@post), success: 'ポストを作成しました'
    else
      @color_palettes = ColorPalette.all  # @color_palettesの設定
      render :new
    end
  end
  

  def edit
    @post = current_user.posts.find(params[:id])
    @category_list = @post.categories.pluck(:category_name).join(',')
  end

  def update
    @post = current_user.posts.find(params[:id])
    category_list = params[:post][:category_name].delete(' ').split(',')
    if @post.update(post_params)
      @post.save_category(category_list)
      redirect_to params[:back_url] || post_path(@post), success: '投稿を編集しました'
    else
      flash.now['danger'] = '編集に失敗しました'
      render :edit
    end
  end
  
  

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:color_palette_id, :body, { images: [] }, :category_names)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/admin_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'admin', media: 'all' %> 
  </head>
  <body class="hold-transition login-page">
    <div>
      <%= render 'admin/shared/flash_message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <meta lang='ja'>
    <meta name="robots" content="noindex, nofollow">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  </head>

  <body class="hold-transition sidebar-mini">
  <div class="wrapper">

    <%= render 'admin/shared/header' %>  
    <%= render 'admin/shared/sidebar' %>
 
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
     <%= render 'admin/shared/flash_message' %> 
     <%= yield %>
    </div>
    <!-- /.content-wrapper -->

    <%= render 'admin/shared/footer' %> 

  </div>
  <%= javascript_pack_tag 'admin' %> 
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
	<a href="/" class="navbar-brand">ColorTips</a>  		
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	<!-- Collection of nav links, forms, and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
		<form class="navbar-form form-inline">
    <div class="input-group search-box">
    <%= search_form_for @search, url: posts_path do |f| %>
      <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-search"></i></span>
      </div>
      <%= f.text_field :color_palette_colors_closest_palette_color_or_categories_category_name_or_body_cont, class: "form-control", placeholder: "Search..." %>
    <% end %>
  </div>
		</form>
		<div class="navbar-nav ml-auto action-buttons">
    <%= link_to 'ログイン', login_path, class: 'nav-link' %>
		</div>
    <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-display="static" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          その他
          </a>
          <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/about">About</a>
            <a class="dropdown-item" href="#">プライバシーポリシー</a>
            <a class="dropdown-item" href="#">利用規約</a>
            <a class="dropdown-item" href="#">お問合せ</a>
          </div>
    </div>

	</div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id= "error_messages" class= "alert alert-danger">
    <ul class="mb-0">
        <% object.errors.full_messages.each do |msg|%>
            <li><%= msg %></li>
        <%end%>
    </ul>
  </div>
 <% end %>     

app/views/shared/_header.html.erb
<div class="navbar navbar-expand-lg navbar-light bg-light">
	<a href="/" class="navbar-brand">ColorTips</a>  		
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
		<span class="navbar-toggler-icon"></span>
	</button>
	<!-- Collection of nav links, forms, and other content for toggling -->
	<div id="navbarCollapse" class="collapse navbar-collapse d-flex justify-content-between">
		<div class="navbar-nav d-flex nav-item-custom">			
			<a href="/color_palettes/new" class="nav-item nav-link flex-grow-custom"><i class="fa-solid fa-palette"></i>色分析</a>
			<a href="/posts/new" class="nav-item nav-link flex-grow-custom"><i class="fa-solid fa-pen-to-square"></i> 新規投稿</a>
		</div>
		<div class="navbar-form form-inline flex-grow-custom">
      <div class="input-group search-box">
        <%= search_form_for @search,html: { class: 'flex-form' }, url: posts_path, method: :get do |f| %>
          <%= f.search_field :color_palette_colors_closest_palette_color_or_categories_category_name_or_body_cont, class: "form-control", placeholder: "Search..." %>
          <div class="input-group-append">
            <button class="btn btn-secondary" type="button">
              <i class="fa fa-search"></i>
            </button>
          </div> 
        <% end %>
      </div>
		</div>
		<div class="navbar-nav ml-auto action-buttons">
      <%= link_to user_path(current_user), class: "dropdown-item" do %>
        <i class="fa-solid fa-user"></i> マイページ
      <% end %>
		</div>
    <div class="nav-item dropdown nav-item-custom">
          <a class="nav-link dropdown-toggle flex-grow-custom" href="#" id="navbarDropdown" role="button" data-display="static" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Other
          </a>
          <div class="dropdown-menu dropdown-menu-lg-left dropdown-menu-left" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/about">About</a>
            <a class="dropdown-item" href="#">プライバシーポリシー</a>
            <a class="dropdown-item" href="#">利用規約</a>
            <a class="dropdown-item" href="#">お問合せ</a>
            <a class="dropdown-item" href="/logout" data-method="DELETE">ログアウト</a>
          </div>
    </div>

	</div>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>