config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :posts
    resources :colors
  end

  get 'about', to: 'pages#about'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'



  resources :users
  resource :profile, only: %i[show edit update]

  resources :color_palettes do
    post 'analyze', on: :collection
  end

  resources :posts, shallow: true do
    resources :categories
  end

  resources :posts do
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

  resources :posts do   
    resources :comments, only: [:create, :destroy]  
  end

  resources :color_palettes do
    delete :delete, on: :member
  end

  resources :posts do
    collection do
      get :search, to: 'posts#search'
    end
  end

  get 'bookmarked_posts', to: 'posts#bookmarked'

  resources :users do
    resources :posts
  end

  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploaders :images, ImageUploader
  belongs_to :user
  belongs_to :color_palette
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :bookmarks, source: :user
  has_many :comments, dependent: :destroy
  validates :color_palette_id, presence: { message: 'カラーパレットを選択してください' }
  validates :images, presence: { message: '画像を選択してください' }

  attr_accessor :category_names

  def save_category(sent_categories)
    categories.clear # 一旦現在のカテゴリを全て削除する
    sent_categories.each do |category_name|
      category = Category.find_or_create_by(category_name: category_name)
      categories << category unless categories.include?(category)
    end
  end

  def selected_colors
    self.color_palette.color_palette_colors.sample(2).map(&:color)
  end

  
  def recommended_posts
    Post.joins(color_palette: :color_palette_colors)
        .where(color_palette_colors: { color_id: self.selected_colors.map(&:id) })
        .where.not(id: self.id)
        .distinct
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to admin_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:color_palette_id, :body, { images: [] }, :category_names)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: %i[index show]

  def index
    @posts = Post.all.includes(:user).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.html { render 'posts/_show' }
      format.js 
    end
  end
  

  def new
    @post = Post.new(user_id: current_user.id)
    @color_palettes = current_user.color_palettes
  end

  def create
    @post = current_user.posts.build(post_params)
    category_list = params[:post][:category_name].split(',')
    if @post.save
      @post.save_category(category_list)
      redirect_to root_path(@post), success: 'ポストを作成しました'
    else
      @color_palettes = ColorPalette.all  # @color_palettesの設定
      render :new
    end
  end
  

  def edit
    @post = current_user.posts.find(params[:id])
    @category_list = @post.categories.pluck(:category_name).join(',')
  end

  def update
    @post = current_user.posts.find(params[:id])
    category_list = params[:post][:category_name].delete(' ').split(',')
    if @post.update(post_params)
      @post.save_category(category_list)
      redirect_to params[:back_url] || post_path(@post), success: '投稿を編集しました'
    else
      flash.now['danger'] = '編集に失敗しました'
      render :edit
    end
  end
  
  

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:color_palette_id, :body, { images: [] }, :category_names)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= javascript_pack_tag 'new_post' %>
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <%= form_with(model: @post, id: 'post_form', url: posts_path, local: true) do |form| %>
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="col-lg-6">
            <!-- Image Upload -->
            <div class="card">
              <div class="card-body">
                <div class="form-group">
                  <%= form.file_field :images, id: 'images', multiple: true, class: 'form-control' %>
                </div>
                <div class="preview-images">
                  <!-- Images will be appended here -->
                </div>
              </div>
            </div>
          </div>

          <!-- Form Input -->
          <div class="col-lg-6">
            <div class="card">
              <div class="card-header bg-light ">Body</div>
              <div class="card-body">
                <div class="form-group">
                  <%= form.text_area :body, rows: 5, class: 'form-control' %>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="card-header bg-light ">Category</div>
              <div class="card-body">
                <div class="form-group">
                  <%= form.text_field :category_name, placeholder: "ここにカテゴリを入力(カンマ区切り)", value: @category_list, class: 'form-control', style: 'width: 300px;' %>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="card-header bg-light">Choose Color Palette:</div>
              <div class="card-body">
                <div class="row">
                  <% @color_palettes.each_with_index do |color_palette, index| %>
                    <div class="col-4 color-palette-selection" id="color-palette-<%= index %>" data-id="<%= color_palette.id %>">
                      <h3 style="font-size: 10px;"><%= color_palette.color_palette_title %></h3>
                      <div class="color_palette">
                        <% color_palette.colors.each do |color| %>
                          <div class="color-row custom-width" style="height: 20px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                        <% end %>
                      </div> 
                    </div>    
                  <% end %>  
                </div>
                <%= form.hidden_field :color_palette_id, id: "selected-palette-id" %>
              </div>
            </div>
          </div>
        </div>
        <div class="text-right">
          <%= form.submit "投稿", class: "btn btn-primary mt-4" %>
        </div>
      <% end %>
    </div>
  </div>    
</div>

app/views/posts/_show.html.erb
<head>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<p>Posted by: <%= link_to @post.user.name, user_path(@post.user) %>

<div class="container-show">
    <div class="row">
      <div class="color-palette-show DivLink">
        <% @post.color_palette.colors.each do |color| %>
          <div class="color-row-show" style="width: 70px; background-color:<%= color.closest_palette_color_html_code %>">
          <a class ="Link" href="?q[color_palette_colors_closest_palette_color_or_categories_category_name_or_body_cont]=<%=color.closest_palette_color %>"></a>
          </div>
        <% end %>
      </div>
    </div>  

    <div id="carouselExample" class="carousel slide" data-interval="false">
        <div class="carousel-inner">
            <% @post.images.each_with_index do |image, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
                <%= image_tag image.to_s, class: "postimage d-block w-90" %>
            </div>
            <% end %>
        </div>  
        <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <%= render "bookmarks/bookmark", post: @post %>  
</div>


<div class="owter-container">
 <div class="inner-container">
    <%= @post.body %>
 </div>   
</div>
<div class="owter-container">
    <% @post.categories.each do |category| %>
    <span class="badge rounded-pill bg-secondary"><%= category.category_name %></span>
    <% unless category.equal?(@post.categories.last) %>
    <% end %>
    <% end %>
</div>
<div id="comments" class="owter-container">
  <% @post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>  
<div class="owter-container">
<%= form_with(model: [ @post, Comment.new ], local: false, id: "new_comment") do |form| %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.text_area :comment_content, placeholder: "Add a comment..." %>
    <%= form.submit "Submit" %>
  <% end %>  
</div>  
<% if current_user && current_user.id == @post.user_id %>
  <div class="container">
    <%= link_to "編集", edit_post_path(@post, back_url: request.original_url), class: "btn btn-primary" %>
    <%= button_to "削除", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
  </div>
<% end %> 

<h4>Recommend posts</h4>
<div class="container-userpage">
  <% @post.recommended_posts.each do |post| %>
    <div class="row1">
      <div class="col-sm-2">
        <div class="row"> 
            <div class="color-palette">
                <% post.color_palette.colors.each do |color| %>
                    <div class="color-row" style="width: 28px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                <% end %>
            </div>
        </div>
        <div class="row">      
            <div class="image-container">
              <%= link_to post_path(post), class: 'btn', remote: true, data: { toggle: 'modal', target: '#postModal' } do %>
                  <% if post.images.any? %>
                    <%= image_tag post.images.first.to_s, class: "postimage" %>
                  <% end %>
              <% end %>  
            </div>
        </div>    
      </div>  
    </div>                
  <% end %>
</div>  

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<h1>投稿の編集</h1>

<%= form_with(model: @post, url: post_path(@post), local: true) do |form| %>
    <div class="form-group">
      <%= form.label :color_palette_id %>
      <%= form.collection_select :color_palette_id, current_user.color_palettes, :id, :color_palette_title %>
    </div>
  
    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, rows: 5, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= form.label :images, "投稿画像" %>
      <% @post.images.each do |image| %>
        <div class="image-container">
          <%= image_tag image.to_s, class: "postimage d-block" %>
        </div>
      <% end %>
      <%= form.file_field :images, multiple: true, class: "form-control" %>
    </div>
  
    <div class="form-group">
      <%= form.label :category_name, "New Category" %>
      <%= form.text_field :category_name, value: @category_list %>
    </div>
  
    <%= form.submit 'Edit', class: 'btn btn-primary' %>
<% end %>

  

app/views/posts/index.html.erb
<div class="container-magic-grid">
  <% @search_posts.each do |post| %>
    <div class="row1">
      <div class="col-sm-2">
        <div class="row"> 
          <div class="card-posts d-flex flex-column">
            <div class="d-flex">
              <div class="color-palette mr-3">
                <% post.color_palette.colors.each do |color| %>
                  <div class="color-row" style="width: 28px; background-color:<%= color.closest_palette_color_html_code %>"></div>
                <% end %>
              </div>
              <div class="image-container">
              <%= link_to post_path(post), class: 'btn', remote: true, data: { toggle: 'modal', target: '#postModal' } do %>
                <% if post.images.any? %>
                  <%= image_tag post.images.first.to_s, class: "postimage", style: "max-width: 150px;" %>
                <% end %>
              <% end %>
            </div>
            </div>
            <div class="user-info mt-3">
              <%= image_tag post.user.avatar.url, class: 'user-avatar' if post.user.avatar.present? %>
              <div class="user-name">
                <%= link_to post.user.name, user_path(post.user) %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">ColorTipsへようこそ!</h4>
      </div>
      <div class="modal-body">

        <!-- Add Carousel here -->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="false">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <h3>使い方</h3>
              <h5>Step1</h5>
              <p>ログイン後、ヘッダーメニューの色分析をクリック！</p>
              <p>好きな画像を読み込んでカラーパレットを作成できます。<p>
              <%= image_tag '画面収録 2023-06-04 23.31.55.gif', alt: 'Description of image',class: 'my-image' %> 
            </div>
            <div class="carousel-item">
              <h3></h3>
              <h5>Step2</h5>
              <p>作成したカラーパレットはマイページでいつでも確認できます。</p>
              <%= image_tag '画面収録 2023-06-06 0.40.46.gif', alt: 'Description of image',class: 'my-image' %>
            </div>
            <div class="carousel-item">
              <h3></h3>
              <h5>Step3</h5>
              <p>カラーパレットからインスピレーションを得てカラーパレットと写真を投稿しよう！</p>      
              <%= image_tag '画面収録 2023-06-06 0.05.30.gif',alt: 'Description of image',class: 'my-image' %>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
    </div>
  </div>
</div>




<script>
  document.querySelectorAll('.image-container').forEach(function(container) {
    // このcontainer内のすべてのpostimageについて、高さを取得する
    var images = container.querySelectorAll('.postimage');
    var maxHeight = 0;
    images.forEach(function(image) {
      var height = image.height;
      if (height > maxHeight) {
        maxHeight = height;
      }
    });
    // containerの高さを、color-rowの数で割って求めた高さに設定する
    var palette = container.querySelector('.color-palette');
    var numColors = palette.querySelectorAll('.color-row').length;
    var paletteHeight = maxHeight / numColors;
    palette.style.height = paletteHeight + 'px';
  });
</script>

app/views/posts/new.html.erb
<div class="container">
    <%= render 'form', { post: @post } %>
</div>

app/views/posts/show.html.erb
<head>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<h1>Posts</h1>
<p>Posted by: <%= link_to @post.user.name, user_path(@post.user) %>

<div class="container-show">
    <div class="row">
      <div class="color-palette-show DivLink">
        <% @post.color_palette.colors.each do |color| %>
          <div class="color-row-show" style="width: 28px; background-color:<%= color.closest_palette_color_html_code %>">
          <a class ="Link" href="?q[color_palette_colors_closest_palette_color_or_categories_category_name_or_body_cont]=<%=color.closest_palette_color %>"></a>
          </div>
        <% end %>
      </div>
    </div>  

    <div id="carouselExample" class="carousel slide" data-interval="false">
        <div class="carousel-inner">
            <% @post.images.each_with_index do |image, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
                <%= image_tag image.to_s, class: "postimage d-block w-90" %>
            </div>
            <% end %>
        </div>  
        <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <%= render "bookmarks/bookmark", post: @post %>  
</div>


<div class="container">
  <%= @post.body %>
</div>
<div class="container">
    <strong>Categories:</strong>
    <% @post.categories.each do |category| %>
    <span class="badge rounded-pill bg-secondary"><%= category.category_name %></span>
    <% unless category.equal?(@post.categories.last) %>
        , 
    <% end %>
    <% end %>
</div>  
<% if current_user && current_user.id == @post.user_id %>
  <div class="container">
    <%= link_to "編集", edit_post_path(@post), class: "btn btn-primary" %>
    <%= button_to "削除", post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
  </div>
<% end %> 

   
            

app/views/posts/show.js.erb
$("#postModal .modal-content").html("<%= j render 'posts/show' %>");
$("#postModal").modal('show');